language: rust
script:
- cargo run
- cat test.html
deploy:
  provider: s3
  access_key_id: $access_key_id
  secret_access_key: $secret_access_key
  bucket: $bucket
  skip_cleanup: true
  local_dir: html
